name: Build Test

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Get the commit SHA from triggering workflow
        id: get-sha
        uses: actions/github-script@v7
        with:
          script: return github.event.workflow_run.head_sha;

      - name: Check out the exact commit
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get-sha.outputs.result }}

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon
