name: Deploy

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t kapsulkeaslian:latest .

      - name: Save Docker image to file
        run: docker save kapsulkeaslian:latest -o kapsulkeaslian.tar

      - name: Copy Docker image to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "kapsulkeaslian.tar"
          target: "~/"

      - name: Load and run Docker image on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop kapsulkeaslian || true && docker rm kapsulkeaslian || true
            docker load -i ~/kapsulkeaslian.tar
            docker run -d \
              --name kapsulkeaslian \
              -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=jdbc:postgresql://${{ DB_HOST }}:${{ DB_PORT }}/${{ DB_NAME }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              kapsulkeaslian:latest
